version: '3.1'

services:

  pg-db:
    image: postgres:14.2-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=root
      - POSTGRES_DB=todo
    ports:
      - "5432:5432"